name: Build, Pack and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore HealthCheck.sln

    - name: Build solution
      run: dotnet build HealthCheck.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test HealthCheck.sln --configuration Release --no-build

    - name: Pack project
      run: dotnet pack ./AspNetCore.Diagnostics.HealthChecks.Background/AspNetCore.Diagnostics.HealthChecks.Background.csproj --configuration Release --no-build -o ./nupkg

    - name: Publish to NuGet
      shell: pwsh
      run: |
        Get-ChildItem ./nupkg/*.nupkg | ForEach-Object {
          dotnet nuget push $_.FullName -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
        }
