name: Build on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore HealthCheck.sln

    - name: Build solution
      run: dotnet build HealthCheck.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test HealthCheck.sln --configuration Release --no-build
